### ISSUE TITLE
Add Bakta

### ISSUE THREAD

**Issue by jasmezz** [nf-core/funcscan#119]
### Description of feature

One more annotation tool! Let's include this module as one more annotation option. https://github.com/oschwengers/bakta
And maybe update the module to the most recent bakta version 1.5.

**Comment by jfy133** [comment]
So I tried getting this to work and I'm not particularly happy with it.

1. The database file you have to download is _huge_ (>30GB), but doesn't even include all the files you need, and you have to manually run `amrfinderplus_update` within it (`cd /<path>/<to>/db && mkdir amrfinderplus-db && amrfinder_update --database ./amrfinderplus-db`
2. It is very slow (possibly even slower than prokka, with the same computing resources)
3. It breaks on our test data with an unclear error message:

```
Error executing process > 'NFCORE_FUNCSCAN:FUNCSCAN:BAKTA (sample_1)'

Caused by:
  Process `NFCORE_FUNCSCAN:FUNCSCAN:BAKTA (sample_1)` terminated with an error exit status (1)

Command executed:

  bakta \
       \
      --threads 2 \
      --prefix sample_1 \
      --db db \
       \
       \
      wastewater_metagenome_contigs_1.fasta
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_FUNCSCAN:FUNCSCAN:BAKTA":
      bakta: $( echo $(bakta --version 2>&1) | sed 's/^.*bakta //' )
  END_VERSIONS

Command exit status:
  1

Command output:
  parse genome sequences...
  predicimported: 1320
  	filtered & revised: 1320
  prediccontigs: 1320
  
  start annotation...
  predict tRNAs...
  	found: 11
  predict tmRNAs...
    Filefound: 0
  predict rRNAs...
    Filefound: 1
  predict ncRNAs...
  Exceptfound: 1
  predict ncRNA regions...
  rk dirfound: 3
  predict CRISPR arrays...
  	found: 0
  predict & annotate CDSs...
  	predicted: 651 
  	discarded spurious: 7
  	revised translational exceptions: 0
  RN: Kidetected IPSs: 8

Command error:
  Traceback (most recent call last):
    File "/usr/local/bin/bakta", line 10, in <module>
  parse genome sequences...
  	imported: 1320
  	filtered & revised: 1320
  	contigs: 1320
  
  start annotation...
  predict tRNAs...
  	found: 11
  predict tmRNAs...
  	found: 0
  predict rRNAs...
  	found: 1
  predict ncRNAs...
  	found: 1
  predict ncRNA regions...
  	found: 3
  predict CRISPR arrays...
  	found: 0
  predict & annotate CDSs...
  	predicted: 651 
  	discarded spurious: 7
  	revised translational exceptions: 0
  	detected IPSs: 8
      sys.exit(main())
    File "/usr/local/lib/python3.10/site-packages/bakta/main.py", line 244, in main
      cdss_psc, cdss_pscc, cdss_not_found = psc.search(cdss_not_found)
    File "/usr/local/lib/python3.10/site-packages/bakta/psc.py", line 64, in search
      raise Exception(f'diamond error! error code: {proc.returncode}')
  Exception: diamond error! error code: -9

Work dir:
  /home/jfellows/Documents/git/nf-core/funcscan/testing/work/1d/23e640dd616c666a0831f41e589595

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

Therefore I would suggest we leave this for a future release when Bakta is more mature.

**Comment by jfy133** [comment]
Ok this might be a memory issue, I'm trying on a larger machine and then may re-open

**Comment by jfy133** [comment]
I've uplaoded bkata db to aither, need to actually run the commadn
